name: gtest
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: gtest environment
      run: |
        sudo apt-get install libgtest-dev
        sudo apt install cmake
        cd /usr/src/gtest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo cp ./lib/libgtest*.a /usr/local/lib
        cd ./work/scheme-interpreter/
        . ./setup.sh
        make
        make test
        ./testpl.out
    - name: Test with unittest 
      run: |
        
        
    - name: Test Coverage 
      run: |
